"""new_settings_fields

Revision ID: 1b1526ea39f9
Revises: a1b2c3d4e5f6
Create Date: 2026-05-17 04:30:53.146004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b1526ea39f9'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_settings', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('store_settings', sa.Column('whatsapp_access_token', sa.String(), nullable=False))
    op.add_column('store_settings', sa.Column('whatsapp_template_name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'store_settings', ['user_id'])
    op.create_foreign_key(None, 'store_settings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'store_settings', type_='foreignkey')
    op.drop_constraint(None, 'store_settings', type_='unique')
    op.drop_column('store_settings', 'whatsapp_template_name')
    op.drop_column('store_settings', 'whatsapp_access_token')
    op.drop_column('store_settings', 'user_id')
    # ### end Alembic commands ###
