"""add checkout_url to carts

Revision ID: 1d975b8cdd2a
Revises: f96ad6273883
Create Date: 2026-05-13 16:14:20.996034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d975b8cdd2a'
down_revision: Union[str, None] = 'f96ad6273883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abandoned_carts', sa.Column('checkout_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('abandoned_carts', 'checkout_url')
    # ### end Alembic commands ###
