"""auto_update

Revision ID: 231ba5259721
Revises: 58522870d0a2
Create Date: 2026-05-31 20:06:28.612457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '231ba5259721'
down_revision: Union[str, None] = '58522870d0a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('store_name', sa.String(), nullable=False),
    sa.Column('salla_store_id', sa.String(), nullable=True),
    sa.Column('salla_webhook_secret', sa.String(), nullable=True),
    sa.Column('whatsapp_phone_id', sa.String(), nullable=True),
    sa.Column('whatsapp_access_token', sa.String(), nullable=True),
    sa.Column('whatsapp_webhook_verify_token', sa.String(), nullable=True),
    sa.Column('whatsapp_template_name', sa.String(), nullable=False),
    sa.Column('coupon_code', sa.String(), nullable=True),
    sa.Column('automation_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_delay_hours', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('shipment_review_enabled', sa.Boolean(), nullable=False),
    sa.Column('shipment_review_delay_hours', sa.Integer(), nullable=False),
    sa.Column('shipment_review_template_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_salla_store_id'), 'stores', ['salla_store_id'], unique=True)
    op.create_table('shipment_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('salla_shipment_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('shipment_status', sa.String(), nullable=True),
    sa.Column('tracking_number', sa.String(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('salla_shipment_id', 'store_id', name='uq_shipment_store')
    )
    op.create_table('shipment_message_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('whatsapp_msg_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment_reviews.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('abandoned_carts', sa.Column('store_id', sa.UUID(), nullable=True))
    op.drop_constraint('uq_cart_user', 'abandoned_carts', type_='unique')
    op.create_unique_constraint('uq_cart_store', 'abandoned_carts', ['salla_cart_id', 'store_id'])
    op.drop_constraint('abandoned_carts_user_id_fkey', 'abandoned_carts', type_='foreignkey')
    op.create_foreign_key(None, 'abandoned_carts', 'stores', ['store_id'], ['id'])
    op.drop_column('abandoned_carts', 'user_id')
    op.add_column('customers', sa.Column('store_id', sa.UUID(), nullable=True))
    op.create_unique_constraint('uq_customer_store', 'customers', ['salla_customer_id', 'store_id'])
    op.drop_constraint('customers_user_id_fkey', 'customers', type_='foreignkey')
    op.create_foreign_key(None, 'customers', 'stores', ['store_id'], ['id'])
    op.drop_column('customers', 'user_id')
    op.create_foreign_key(None, 'email_campaigns', 'stores', ['store_id'], ['id'])
    op.add_column('email_contacts', sa.Column('sendgrid_list_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'email_contacts', 'stores', ['store_id'], ['id'])
    op.create_foreign_key(None, 'email_store_settings', 'stores', ['store_id'], ['id'])
    op.create_foreign_key(None, 'email_tracking_logs', 'stores', ['store_id'], ['id'])
    op.add_column('message_logs', sa.Column('store_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'message_logs', 'stores', ['store_id'], ['id'])
    op.add_column('recovered_carts', sa.Column('store_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'recovered_carts', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recovered_carts', type_='foreignkey')
    op.drop_column('recovered_carts', 'store_id')
    op.drop_constraint(None, 'message_logs', type_='foreignkey')
    op.drop_column('message_logs', 'store_id')
    op.drop_constraint(None, 'email_tracking_logs', type_='foreignkey')
    op.drop_constraint(None, 'email_store_settings', type_='foreignkey')
    op.drop_constraint(None, 'email_contacts', type_='foreignkey')
    op.drop_column('email_contacts', 'sendgrid_list_id')
    op.drop_constraint(None, 'email_campaigns', type_='foreignkey')
    op.add_column('customers', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.create_foreign_key('customers_user_id_fkey', 'customers', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_customer_store', 'customers', type_='unique')
    op.drop_column('customers', 'store_id')
    op.add_column('abandoned_carts', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'abandoned_carts', type_='foreignkey')
    op.create_foreign_key('abandoned_carts_user_id_fkey', 'abandoned_carts', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_cart_store', 'abandoned_carts', type_='unique')
    op.create_unique_constraint('uq_cart_user', 'abandoned_carts', ['salla_cart_id', 'user_id'])
    op.drop_column('abandoned_carts', 'store_id')
    op.drop_table('shipment_message_logs')
    op.drop_table('shipment_reviews')
    op.drop_index(op.f('ix_stores_salla_store_id'), table_name='stores')
    op.drop_table('stores')
    # ### end Alembic commands ###
