"""campaign_contacts

Revision ID: 24c47f31780e
Revises: c0c822a4ec23
Create Date: 2026-06-05 01:14:04.973479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24c47f31780e'
down_revision: Union[str, None] = 'c0c822a4ec23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_campaign_contacts',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['email_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['email_contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', 'contact_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_campaign_contacts')
    # ### end Alembic commands ###
