"""add_email_marketing_warmup_and_sync_features

Revision ID: 2ca7dd2a34cc
Revises: 9beaaf7dbb1e
Create Date: 2026-06-05 16:49:46.674194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ca7dd2a34cc'
down_revision: Union[str, None] = '9beaaf7dbb1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_lists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('sg_list_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_lists_sg_list_id'), 'email_lists', ['sg_list_id'], unique=True)
    op.create_table('email_senders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('sg_sender_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('from_email', sa.String(), nullable=False),
    sa.Column('from_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_senders_sg_sender_id'), 'email_senders', ['sg_sender_id'], unique=True)
    op.create_table('email_suppression_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('sg_group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_suppression_groups_sg_group_id'), 'email_suppression_groups', ['sg_group_id'], unique=True)
    op.create_table('email_campaign_contacts',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['email_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['email_contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', 'contact_id')
    )
    op.alter_column('abandoned_carts', 'store_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('customer_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('customer_reviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'store_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('email_campaigns', sa.Column('is_warmup', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('email_campaigns', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.add_column('email_campaigns', sa.Column('warmup_day', sa.Integer(), nullable=True))
    op.add_column('email_campaigns', sa.Column('warmup_current_offset', sa.Integer(), server_default='0', nullable=False))
    op.create_foreign_key(None, 'email_campaigns', 'email_campaigns', ['parent_id'], ['id'])
    op.add_column('email_contacts', sa.Column('validation_status', sa.String(), nullable=False))
    op.add_column('email_contacts', sa.Column('validation_reason', sa.String(), nullable=True))
    op.add_column('email_contacts', sa.Column('has_mx', sa.Boolean(), nullable=True))
    op.add_column('email_contacts', sa.Column('mx_host', sa.String(), nullable=True))
    op.add_column('email_contacts', sa.Column('smtp_valid', sa.Boolean(), nullable=True))
    op.add_column('email_store_settings', sa.Column('validation_delay_hours', sa.Integer(), server_default='0', nullable=False))
    op.add_column('email_store_settings', sa.Column('validate_smtp', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('email_store_settings', sa.Column('validate_mx', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('email_store_settings', sa.Column('validate_spelling', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('email_store_settings', sa.Column('warmup_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('email_store_settings', sa.Column('warmup_current_day', sa.Integer(), server_default='1', nullable=False))
    op.alter_column('message_logs', 'store_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('recovered_carts', 'store_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recovered_carts', 'store_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('message_logs', 'store_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('email_store_settings', 'warmup_current_day')
    op.drop_column('email_store_settings', 'warmup_enabled')
    op.drop_column('email_store_settings', 'validate_spelling')
    op.drop_column('email_store_settings', 'validate_mx')
    op.drop_column('email_store_settings', 'validate_smtp')
    op.drop_column('email_store_settings', 'validation_delay_hours')
    op.drop_column('email_contacts', 'smtp_valid')
    op.drop_column('email_contacts', 'mx_host')
    op.drop_column('email_contacts', 'has_mx')
    op.drop_column('email_contacts', 'validation_reason')
    op.drop_column('email_contacts', 'validation_status')
    op.drop_constraint(None, 'email_campaigns', type_='foreignkey')
    op.drop_column('email_campaigns', 'warmup_current_offset')
    op.drop_column('email_campaigns', 'warmup_day')
    op.drop_column('email_campaigns', 'parent_id')
    op.drop_column('email_campaigns', 'is_warmup')
    op.alter_column('customers', 'store_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('customer_reviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('customer_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('abandoned_carts', 'store_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_table('email_campaign_contacts')
    op.drop_index(op.f('ix_email_suppression_groups_sg_group_id'), table_name='email_suppression_groups')
    op.drop_table('email_suppression_groups')
    op.drop_index(op.f('ix_email_senders_sg_sender_id'), table_name='email_senders')
    op.drop_table('email_senders')
    op.drop_index(op.f('ix_email_lists_sg_list_id'), table_name='email_lists')
    op.drop_table('email_lists')
    # ### end Alembic commands ###
