"""add whatsapp_webhook_verify_token

Revision ID: 58522870d0a2
Revises: aea7deca8c56
Create Date: 2026-05-31 19:45:29.177904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58522870d0a2'
down_revision: Union[str, None] = 'aea7deca8c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('salla_shipment_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('shipment_status', sa.String(), nullable=True),
    sa.Column('tracking_number', sa.String(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('salla_shipment_id', 'store_id', name='uq_shipment_store')
    )
    op.create_table('shipment_message_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('whatsapp_msg_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment_reviews.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('stores', sa.Column('whatsapp_webhook_verify_token', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('shipment_review_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('stores', sa.Column('shipment_review_delay_hours', sa.Integer(), server_default='24', nullable=False))
    op.add_column('stores', sa.Column('shipment_review_template_name', sa.String(), server_default='shipment_review', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'shipment_review_template_name')
    op.drop_column('stores', 'shipment_review_delay_hours')
    op.drop_column('stores', 'shipment_review_enabled')
    op.drop_column('stores', 'whatsapp_webhook_verify_token')
    op.drop_table('shipment_message_logs')
    op.drop_table('shipment_reviews')
    # ### end Alembic commands ###
