"""Add email marketing and apply multi-tenant

Revision ID: 6da3ba68559f
Revises: ed1e93ea96ce
Create Date: 2026-05-29 17:05:26.553784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6da3ba68559f'
down_revision: Union[str, None] = 'ed1e93ea96ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename store_settings to stores
    op.rename_table('store_settings', 'stores')
    
    # Rename user_id to owner_id
    op.alter_column('stores', 'user_id', new_column_name='owner_id')
    
    # Drop old constraints
    op.drop_constraint('store_settings_user_id_fkey', 'stores', type_='foreignkey')
    op.drop_constraint('store_settings_user_id_key', 'stores', type_='unique')
    
    # Add new columns as nullable=True first
    op.add_column('stores', sa.Column('store_name', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('salla_store_id', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('reminder_delay_hours', sa.Integer(), nullable=True))
    op.add_column('stores', sa.Column('max_retries', sa.Integer(), nullable=True))
    op.add_column('stores', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('stores', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('stores', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    
    # Provide default values for NOT NULL columns
    op.execute("UPDATE stores SET store_name = 'Default Store', reminder_delay_hours = 24, max_retries = 3, is_active = true WHERE store_name IS NULL")
    
    # Alter columns to NOT NULL
    op.alter_column('stores', 'store_name', nullable=False)
    op.alter_column('stores', 'reminder_delay_hours', nullable=False)
    op.alter_column('stores', 'max_retries', nullable=False)
    op.alter_column('stores', 'is_active', nullable=False)
    
    # Add new constraint and index
    op.create_foreign_key(None, 'stores', 'users', ['owner_id'], ['id'])
    op.create_index(op.f('ix_stores_salla_store_id'), 'stores', ['salla_store_id'], unique=True)
    op.create_table('email_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('sendgrid_campaign_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_subscribed', sa.Boolean(), nullable=False),
    sa.Column('sync_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uix_email_contacts_store_email', 'email_contacts', ['store_id', 'email'], unique=True)
    op.create_table('email_store_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('sendgrid_api_key', sa.String(), nullable=True),
    sa.Column('sendgrid_default_list_id', sa.String(), nullable=True),
    sa.Column('from_email', sa.String(), nullable=True),
    sa.Column('from_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id')
    )
    op.create_table('email_tracking_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('sendgrid_msg_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['email_campaigns.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['email_contacts.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_tracking_logs_sendgrid_msg_id'), 'email_tracking_logs', ['sendgrid_msg_id'], unique=False)
    op.create_table('recovered_carts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['abandoned_carts.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id')
    )

    op.add_column('abandoned_carts', sa.Column('store_id', sa.UUID(), nullable=True))
    op.execute("""
        UPDATE abandoned_carts 
        SET store_id = (SELECT id FROM stores WHERE stores.owner_id = abandoned_carts.user_id LIMIT 1)
    """)
    op.alter_column('abandoned_carts', 'store_id', nullable=False)
    
    op.drop_constraint('uq_cart_user', 'abandoned_carts', type_='unique')
    op.create_unique_constraint('uq_cart_store', 'abandoned_carts', ['salla_cart_id', 'store_id'])
    op.drop_constraint('abandoned_carts_user_id_fkey', 'abandoned_carts', type_='foreignkey')
    op.create_foreign_key(None, 'abandoned_carts', 'stores', ['store_id'], ['id'])
    op.drop_column('abandoned_carts', 'user_id')
    op.add_column('customers', sa.Column('store_id', sa.UUID(), nullable=True))
    op.execute("""
        UPDATE customers 
        SET store_id = (SELECT id FROM stores WHERE stores.owner_id = customers.user_id LIMIT 1)
    """)
    op.alter_column('customers', 'store_id', nullable=False)
    
    op.create_unique_constraint('uq_customer_store', 'customers', ['salla_customer_id', 'store_id'])
    op.drop_constraint('customers_user_id_fkey', 'customers', type_='foreignkey')
    op.create_foreign_key(None, 'customers', 'stores', ['store_id'], ['id'])
    op.drop_column('customers', 'user_id')
    op.add_column('message_logs', sa.Column('store_id', sa.UUID(), nullable=True))
    op.execute("""
        UPDATE message_logs 
        SET store_id = COALESCE(
            (SELECT store_id FROM abandoned_carts WHERE abandoned_carts.id = message_logs.cart_id LIMIT 1),
            (SELECT id FROM stores LIMIT 1)
        )
    """)
    op.alter_column('message_logs', 'store_id', nullable=False)
    op.create_foreign_key(None, 'message_logs', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message_logs', type_='foreignkey')
    op.drop_column('message_logs', 'store_id')
    op.add_column('customers', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.create_foreign_key('customers_user_id_fkey', 'customers', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_customer_store', 'customers', type_='unique')
    op.drop_column('customers', 'store_id')
    op.add_column('abandoned_carts', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'abandoned_carts', type_='foreignkey')
    op.create_foreign_key('abandoned_carts_user_id_fkey', 'abandoned_carts', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_cart_store', 'abandoned_carts', type_='unique')
    op.create_unique_constraint('uq_cart_user', 'abandoned_carts', ['salla_cart_id', 'user_id'])
    op.drop_column('abandoned_carts', 'store_id')
    op.drop_index(op.f('ix_stores_salla_store_id'), table_name='stores')
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_column('stores', 'updated_at')
    op.drop_column('stores', 'created_at')
    op.drop_column('stores', 'is_active')
    op.drop_column('stores', 'max_retries')
    op.drop_column('stores', 'reminder_delay_hours')
    op.drop_column('stores', 'salla_store_id')
    op.drop_column('stores', 'store_name')
    op.alter_column('stores', 'owner_id', new_column_name='user_id')
    op.rename_table('stores', 'store_settings')
    op.create_foreign_key('store_settings_user_id_fkey', 'store_settings', 'users', ['user_id'], ['id'])
    op.create_unique_constraint('store_settings_user_id_key', 'store_settings', ['user_id'])
    op.drop_table('recovered_carts')
    op.drop_index(op.f('ix_email_tracking_logs_sendgrid_msg_id'), table_name='email_tracking_logs')
    op.drop_table('email_tracking_logs')
    op.drop_table('email_store_settings')
    op.drop_index('uix_email_contacts_store_email', table_name='email_contacts')
    op.drop_table('email_contacts')
    op.drop_table('email_campaigns')

    # ### end Alembic commands ###
