"""rename salla_api_key to salla_webhook_secret

Revision ID: a00389c26be3
Revises: f98caa73881a
Create Date: 2026-05-17 23:16:51.859400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a00389c26be3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('store_settings', 'salla_api_key', new_column_name='salla_webhook_secret')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('store_settings', 'salla_webhook_secret', new_column_name='salla_api_key')
    # ### end Alembic commands ###
