"""Add email validation columns

Revision ID: a633a09717bf
Revises: 0b0572ceb75b
Create Date: 2026-06-04 23:57:23.862835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a633a09717bf'
down_revision: Union[str, None] = '0b0572ceb75b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_contacts', sa.Column('validation_status', sa.String(), server_default='pending', nullable=False))
    op.add_column('email_contacts', sa.Column('validation_reason', sa.String(), nullable=True))
    op.add_column('email_contacts', sa.Column('has_mx', sa.Boolean(), nullable=True))
    op.add_column('email_contacts', sa.Column('mx_host', sa.String(), nullable=True))
    op.add_column('email_contacts', sa.Column('smtp_valid', sa.Boolean(), nullable=True))
    op.add_column('stores', sa.Column('reminder_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'reminder_image_url')
    op.drop_column('email_contacts', 'smtp_valid')
    op.drop_column('email_contacts', 'mx_host')
    op.drop_column('email_contacts', 'has_mx')
    op.drop_column('email_contacts', 'validation_reason')
    op.drop_column('email_contacts', 'validation_status')
    # ### end Alembic commands ###
