"""add sendgrid_list_id to email_contacts

Revision ID: aea7deca8c56
Revises: 6da3ba68559f
Create Date: 2026-05-29 17:59:27.268613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aea7deca8c56'
down_revision: Union[str, None] = '6da3ba68559f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_contacts', sa.Column('sendgrid_list_id', sa.String(), nullable=True))
    op.alter_column('stores', 'salla_webhook_secret',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stores', 'whatsapp_phone_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stores', 'whatsapp_access_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stores', 'automation_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'automation_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('stores', 'whatsapp_access_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stores', 'whatsapp_phone_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stores', 'salla_webhook_secret',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('email_contacts', 'sendgrid_list_id')
    # ### end Alembic commands ###
