"""validation_settings

Revision ID: c0c822a4ec23
Revises: a633a09717bf
Create Date: 2026-06-05 00:38:17.242649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0c822a4ec23'
down_revision: Union[str, None] = 'a633a09717bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_store_settings', sa.Column('validation_delay_hours', sa.Integer(), server_default='0', nullable=False))
    op.add_column('email_store_settings', sa.Column('validate_smtp', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('email_store_settings', sa.Column('validate_mx', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('email_store_settings', sa.Column('validate_spelling', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_store_settings', 'validate_spelling')
    op.drop_column('email_store_settings', 'validate_mx')
    op.drop_column('email_store_settings', 'validate_smtp')
    op.drop_column('email_store_settings', 'validation_delay_hours')
    # ### end Alembic commands ###
