"""migiration

Revision ID: c159bc765b79
Revises: 
Create Date: 2026-05-18 11:00:17.380479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c159bc765b79'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    import uuid
    from app.core.security import hash_password

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    # 1. Insert reiash user
    reiash_id = str(uuid.uuid4())
    hashed_pwd = hash_password("reiash123")
    op.execute(
        f"INSERT INTO users (id, username, email, hashed_password, is_admin, is_active, created_at, updated_at) "
        f"VALUES ('{reiash_id}', 'reiash', 'reiash@example.com', '{hashed_pwd}', true, true, NOW(), NOW())"
    )

    # 2. Add columns as nullable=True first
    op.add_column('abandoned_carts', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('customers', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('store_settings', sa.Column('user_id', sa.UUID(), nullable=True))

    # 3. Update existing records to link to reiash user
    op.execute(f"UPDATE abandoned_carts SET user_id = '{reiash_id}'")
    op.execute(f"UPDATE customers SET user_id = '{reiash_id}'")
    op.execute(f"UPDATE store_settings SET user_id = '{reiash_id}'")

    # 4. Alter columns to NOT NULL
    op.alter_column('abandoned_carts', 'user_id', nullable=False)
    op.alter_column('customers', 'user_id', nullable=False)
    op.alter_column('store_settings', 'user_id', nullable=False)

    # Rest of constraints for abandoned_carts
    op.drop_index('ix_abandoned_carts_salla_cart_id', table_name='abandoned_carts')
    op.create_index(op.f('ix_abandoned_carts_salla_cart_id'), 'abandoned_carts', ['salla_cart_id'], unique=False)
    op.create_unique_constraint('uq_cart_user', 'abandoned_carts', ['salla_cart_id', 'user_id'])
    op.create_foreign_key(None, 'abandoned_carts', 'users', ['user_id'], ['id'])

    # Rest of constraints for customers
    op.drop_index('ix_customers_salla_customer_id', table_name='customers')
    op.create_index(op.f('ix_customers_salla_customer_id'), 'customers', ['salla_customer_id'], unique=False)
    op.create_foreign_key(None, 'customers', 'users', ['user_id'], ['id'])

    # Rest of constraints for store_settings
    # Safely add whatsapp_access_token
    op.add_column('store_settings', sa.Column('whatsapp_access_token', sa.String(), nullable=True))
    op.execute("UPDATE store_settings SET whatsapp_access_token = 'EAA...' WHERE whatsapp_access_token IS NULL")
    op.alter_column('store_settings', 'whatsapp_access_token', nullable=False)

    # Safely add whatsapp_template_name
    op.add_column('store_settings', sa.Column('whatsapp_template_name', sa.String(), nullable=True))
    op.execute("UPDATE store_settings SET whatsapp_template_name = 'hello_world' WHERE whatsapp_template_name IS NULL")
    op.alter_column('store_settings', 'whatsapp_template_name', nullable=False)

    # If coupon_code was already added manually (as we did in the scratch_test script earlier), adding it again will fail.
    # We should use 'IF NOT EXISTS' but alembic doesn't support it directly.
    # We can check if column exists before adding it using a raw execute or inspector.
    from sqlalchemy.engine.reflection import Inspector
    bind = op.get_context().bind
    inspector = Inspector.from_engine(bind)
    columns = [col['name'] for col in inspector.get_columns('store_settings')]
    
    if 'coupon_code' not in columns:
        op.add_column('store_settings', sa.Column('coupon_code', sa.String(), nullable=True))

    op.create_unique_constraint(None, 'store_settings', ['user_id'])
    op.create_foreign_key(None, 'store_settings', 'users', ['user_id'], ['id'])

    if 'store_name' in columns:
        op.drop_column('store_settings', 'store_name')
    if 'max_retries' in columns:
        op.drop_column('store_settings', 'max_retries')
    if 'reminder_delay_hours' in columns:
        op.drop_column('store_settings', 'reminder_delay_hours')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_settings', sa.Column('reminder_delay_hours', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('store_settings', sa.Column('max_retries', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('store_settings', sa.Column('store_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'store_settings', type_='foreignkey')
    op.drop_constraint(None, 'store_settings', type_='unique')
    op.drop_column('store_settings', 'coupon_code')
    op.drop_column('store_settings', 'whatsapp_template_name')
    op.drop_column('store_settings', 'whatsapp_access_token')
    op.drop_column('store_settings', 'user_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_salla_customer_id'), table_name='customers')
    op.create_index('ix_customers_salla_customer_id', 'customers', ['salla_customer_id'], unique=False)
    op.drop_column('customers', 'user_id')
    op.drop_constraint(None, 'abandoned_carts', type_='foreignkey')
    op.drop_constraint('uq_cart_user', 'abandoned_carts', type_='unique')
    op.drop_index(op.f('ix_abandoned_carts_salla_cart_id'), table_name='abandoned_carts')
    op.create_index('ix_abandoned_carts_salla_cart_id', 'abandoned_carts', ['salla_cart_id'], unique=False)
    op.drop_column('abandoned_carts', 'user_id')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
