"""simplify_store_settings

Revision ID: c4729df09809
Revises: 1b1526ea39f9
Create Date: 2026-05-17 22:04:31.315036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4729df09809'
down_revision: Union[str, None] = '1b1526ea39f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abandoned_carts', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_abandoned_carts_salla_cart_id'), table_name='abandoned_carts')
    op.create_index(op.f('ix_abandoned_carts_salla_cart_id'), 'abandoned_carts', ['salla_cart_id'], unique=False)
    op.create_unique_constraint('uq_cart_user', 'abandoned_carts', ['salla_cart_id', 'user_id'])
    op.create_foreign_key(None, 'abandoned_carts', 'users', ['user_id'], ['id'])
    op.add_column('customers', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_customers_salla_customer_id'), table_name='customers')
    op.create_index(op.f('ix_customers_salla_customer_id'), 'customers', ['salla_customer_id'], unique=False)
    op.create_foreign_key(None, 'customers', 'users', ['user_id'], ['id'])
    op.drop_column('store_settings', 'store_name')
    op.drop_column('store_settings', 'reminder_delay_hours')
    op.drop_column('store_settings', 'max_retries')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_settings', sa.Column('max_retries', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('store_settings', sa.Column('reminder_delay_hours', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('store_settings', sa.Column('store_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_salla_customer_id'), table_name='customers')
    op.create_index(op.f('ix_customers_salla_customer_id'), 'customers', ['salla_customer_id'], unique=True)
    op.drop_column('customers', 'user_id')
    op.drop_constraint(None, 'abandoned_carts', type_='foreignkey')
    op.drop_constraint('uq_cart_user', 'abandoned_carts', type_='unique')
    op.drop_index(op.f('ix_abandoned_carts_salla_cart_id'), table_name='abandoned_carts')
    op.create_index(op.f('ix_abandoned_carts_salla_cart_id'), 'abandoned_carts', ['salla_cart_id'], unique=True)
    op.drop_column('abandoned_carts', 'user_id')
    # ### end Alembic commands ###
