"""make_salla_webhook_secret_optional

Revision ID: e069688550c9
Revises: a00389c26be3
Create Date: 2026-05-18 10:37:41.763411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e069688550c9'
down_revision: Union[str, None] = 'a00389c26be3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('store_settings', 'salla_webhook_secret',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('store_settings', 'salla_webhook_secret',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
