"""Initial migration

Revision ID: f96ad6273883
Revises: 
Create Date: 2026-05-13 13:30:04.657124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f96ad6273883'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('salla_customer_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('mobile', sa.String(), nullable=False),
    sa.Column('mobile_code', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('total_carts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_salla_customer_id'), 'customers', ['salla_customer_id'], unique=True)
    op.create_table('store_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_name', sa.String(), nullable=False),
    sa.Column('salla_api_key', sa.String(), nullable=False),
    sa.Column('whatsapp_phone_id', sa.String(), nullable=False),
    sa.Column('automation_enabled', sa.Boolean(), nullable=True),
    sa.Column('reminder_delay_hours', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('abandoned_carts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('salla_cart_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('cart_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('reminder_sent', sa.Boolean(), nullable=True),
    sa.Column('is_recovered', sa.Boolean(), nullable=True),
    sa.Column('abandoned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abandoned_carts_salla_cart_id'), 'abandoned_carts', ['salla_cart_id'], unique=True)
    op.create_table('message_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('whatsapp_msg_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['abandoned_carts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_logs')
    op.drop_index(op.f('ix_abandoned_carts_salla_cart_id'), table_name='abandoned_carts')
    op.drop_table('abandoned_carts')
    op.drop_table('store_settings')
    op.drop_index(op.f('ix_customers_salla_customer_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
