"""add_coupon_code_to_settings

Revision ID: f98caa73881a
Revises: c4729df09809
Create Date: 2026-05-17 22:45:44.086258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f98caa73881a'
down_revision: Union[str, None] = 'c4729df09809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_settings', sa.Column('coupon_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_settings', 'coupon_code')
    # ### end Alembic commands ###
